version: "3.7"
services:
  php:
    build: './php/'
    ports:
        - 80:80
    volumes:
      - ./src/:/var/www/html/
      - ./db/:/var/www/db/
      - ./apache/demo.apache.conf:/etc/apache2/sites-enabled/demo.conf